name = "new_lean"
version = "0.1.0"
# We only want to build the library, not a standalone app
defaultTargets = ["NewLean"]

[[lean_lib]]
name = "NewLean"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"